# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/cocoapods/specs'

target 'twilio' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for twilio

  target 'twilioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'TwilioVoice', '~> 2.0.0'

end

target 'twilio-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for twilio-tvOS

  target 'twilio-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
